### ISSUE TITLE
提示“登录失败！疑似修改登录系统！”

### ISSUE THREAD

**Issue by helijiqunQAQ** [Lanszhang131/DailyReport_SHU#1]

**Comment by Lanszhang131** [comment]
我这边测试还可以的，有完整的报错信息吗

**Comment by helijiqunQAQ** [comment]
![1](https://user-images.githubusercontent.com/57850668/105807185-7f6b8d00-5fe0-11eb-85b1-f8070cb95400.png)

**Comment by Lanszhang131** [comment]
可能是学号密码没写对。看一下all_stu.json里是不是你写的学号密码

**Comment by helijiqunQAQ** [comment]
好像读不到students里的信息，我手动改all_stu.json里的学号密码后登陆成功了。然后它提示我还要装一个lxml库

**Comment by helijiqunQAQ** [comment]
![2](https://user-images.githubusercontent.com/57850668/105808677-22bda180-5fe3-11eb-95f9-caa73f094795.png)

**Comment by helijiqunQAQ** [comment]
然后又有奇怪的问题出现了（
![3](https://user-images.githubusercontent.com/57850668/105808988-cc9d2e00-5fe3-11eb-8c06-2da2106eda9a.png)

**Comment by Lanszhang131** [comment]
那个不能读student的问题你可以把代码中的student路径换为绝对路径，‘lxml’的问题你应该解决了吧，pip install 一下就行了，第三个问题的话，你可以debug一下，看看self.stu_dic['addr_2']是不是取了三大坨东西。
![image](https://user-images.githubusercontent.com/50519601/105809556-dd9a6f00-5fe4-11eb-960a-244971530bf6.png)

**Comment by Lanszhang131** [comment]
不对，它没有报student路径不存在，那应该不是路径的问题，应该是txt文件的原因，很有可能是windows神奇的解码问题？？我用的是mac，到时候拿windows试试看

**Comment by helijiqunQAQ** [comment]
lxml问题解决了，我看看后面那个是啥问题

**Comment by Lanszhang131** [comment]
我拿win也试过了，能跑通，再确保一下文件结构吧，一定要和项目保持一致。另外就是debug查看一下我刚刚说的self.stu_dic['addr_2']，假如不会debug的话就在图中的位置加入一行代码 ` print(self.stu_dic['addr_2'] ` 

![image](https://user-images.githubusercontent.com/50519601/105812767-b8f4c600-5fe9-11eb-91c5-60b97ddd91c9.png)

**Comment by helijiqunQAQ** [comment]
好像没有获取到地址，输出了一个[]

**Comment by Lanszhang131** [comment]
明白了，取地址那块有问题，可能每个人的上报页面还是会有不同，有些页面可能地址栏隐藏了，导致我取不到，晚些时候更新一下，从前一天的报送历史这边取地址吧，你应该有手动报过吧？

**Comment by helijiqunQAQ** [comment]
嗯，报过的

**Comment by Lanszhang131** [comment]
```
    def get_addr_2(self):
        if self.one_or_two == 2:
            return ''
        else:
            
            his = self.sess.get('https://selfreport.shu.edu.cn/ViewDayReport.aspx?day=2021-01-26')
            con = soup(his.text, 'html.parser').findAll('script', {'type': 'text/javascript'})[-1].text
            f_state_val = [i.strip().replace(';', '').split('=')[1] for i in con.split('var') if '={' in i]
            addrs = []
            for i in f_state_val:
                addrs.append(i)
                if len(addrs)>3 and '选择县区' in addrs[-2]:
                    break
            return [eval(i.replace("true", 'True').replace('false', 'False')) for i in addrs[-4:]]
```
把原来的get_addr_2()换成这个试试，假如这个可以的话，我今天就做一下修改吧

**Comment by helijiqunQAQ** [comment]
还是不对，取不到地址
![4](https://user-images.githubusercontent.com/57850668/105818066-66b7a300-5ff1-11eb-9209-70b1921dbc9f.png)

**Comment by Lanszhang131** [comment]
神奇，这个就有点不科学了，你像下面图一样在函数里加两行代码，跑一下，然后把生成的error.txt文件发给我吧，lance131z@163.com
![image](https://user-images.githubusercontent.com/50519601/105818748-3fada100-5ff2-11eb-932c-2dda6aeab540.png)

**Comment by helijiqunQAQ** [comment]
ok发过去了

**Comment by Lanszhang131** [comment]
ok已解决，是win7 python BeautifulSoup的问题，需要把`con = soup(his.text, 'html.parser').findAll('script', {'type': 'text/javascript'})[-1].text` 改为`con = soup(his.text, 'html.parser').findAll('script', {'type': 'text/javascript'})[-1].string`
